version: "3.9"

services:
  php-fpm:
    image: php:fpm-alpine3.13
    container_name: php-fpm
    volumes:
      - ./public_html:/var/www/html
    environment:
      - VIRTUAL_HOST=current.aws.cisassessment.com.br
      - LETSENCRYPT_HOST=current.aws.cisassessment.com.br
      - VIRTUAL_PROTO=fastcgi
      - LETSENCRYPT_EMAIL=leandro@cisassessment.com.br

networks:
  default:
    external:
      name: proxy
